##########
### Start
##########

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Endless Parentheses
tagline:          'Concise ramblings on Emacs productivity.'
url:              'http://endlessparentheses.com'
paginate:         8

baseurl:          /
author:
  name:           Artur Malabarba
  url:            https://github.com/Bruce-Connor
  email:          bruce.connor.am@gmail.com
  twitter:        https://twitter.com/bruceconnor

# Content
excerpt_separator: "</p>"
timezone:         UTC
future:           false

# This doesn't work, had to implement my own solution.
# lsi:              true

# Related pages
related:
  excluded_tags:  ['init.el', 'emacs']
  max_number:     3

pages_list:
  About: ['/about.html', '/icons/favicon-bw.png']
  Archive: ['/archive.html', '/icons/envelope.png']
  RSS Feed: ['/atom.xml', '/icons/rss.png']
  Tag List: ['/tags.html', '/icons/tag.png']
  Android App: ['http://doc.endlessparentheses.com/app.html', '/icons/android.png']

media_list:
  Twitter:
    url: 'https://twitter.com/intent/tweet?via=BruceConnor&hashtags=emacs&url='
    icon: '/icons/twitter.png'
    title: '&text='
  # Facebook:
  #   url: 'http://facebook.com/sharer.php?u='
  #   icon: '/icons/facebook.png'
  Google Plus:
    url: 'https://plus.google.com/share?hl=en&url='
    icon: '/icons/gplus.png'

projects:
  smart-mode-line:
    url: 'https://github.com/Bruce-Connor/smart-mode-line/'
    description: 'A powerful and beautiful mode-line.'
  Paradox:
    url: 'https://github.com/Bruce-Connor/paradox/'
    description: 'A modern and customizable Packages Menu .'
  # latex-extra:
  #   url: 'https://github.com/Bruce-Connor/latex-extra/'
  #   description: 'A series of usability improvements for LaTeX-mode.'
  google-this:
    url: 'https://github.com/Bruce-Connor/emacs-google-this/'
    description: 'A set of functions and bindings to Google under point.'
  Emacs Online Documentation:
    url: 'http://doc.endlessparentheses.com/'
    description: 'An up-to-date online documentation of ALL Emacs functions and variables.'
  Emacs Documentation Android App:
    url: 'https://play.google.com/store/apps/details?id=com.malabarba.emacsdocumentation'
    description: 'Consult functions and variables on your Android device.'
  Emacs Archive Tracker:
    url: 'http://tracker.endlessparentheses.com/'
    description: 'Statistics on the growth of Emacs package repositories.'

gems:
  - jekyll-sitemap
