##########
### Start
##########

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Endless Parentheses
tagline:          'Concise ramblings on Emacs productivity.'
url:              'http://endlessparentheses.com'
paginate:         8

baseurl:          /
author:
  name:           Artur Malabarba
  url:            https://github.com/Bruce-Connor
  email:          bruce.connor.am@gmail.com
  twitter:        https://twitter.com/bruceconnor

# Content
excerpt_separator: "</p>"
timezone:         UTC
future:           false

# This doesn't work, had to implement my own solution.
# lsi:              true

# Custom vars
version:          1.0.0
github:
  repo:           'https://github.com/Bruce-Connor/EndlessParentheses'

# Related pages
related:
  excluded_tags:  ['init.el', 'emacs']
  max_number:     3

pages_list:
  About: ['/about.html', '/icons/favicon-bw.png']
  Archive: ['/archive.html', '/icons/envelope.png']
  RSS Feed: ['/atom.xml', '/icons/rss.png']
  Tag List: ['/tags.html', '/icons/tag.png']

media_list:
  Twitter:
    url: 'https://twitter.com/intent/tweet?via=BruceConnor&hashtags=emacs&url='
    icon: '/icons/twitter.png'
    title: '&text='
  Facebook:
    url: 'http://facebook.com/sharer.php?u='
    icon: '/icons/facebook.png'
  Google Plus:
    url: 'https://plus.google.com/share?hl=en&url='
    icon: '/icons/gplus.png'

gems:
  - jekyll-sitemap
