# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        none

# Setup
title:            Endless Parentheses
tagline:          'Concise ramblings on Emacs productivity.'
url:              'http://endlessparentheses.com'
paginate:         10

baseurl:          
author:
  name:           Artur Malabarba
  url:            https://github.com/Bruce-Connor
  email:          bruce.connor.am@gmail.com

# Content
excerpt_separator: "</p>"
lsi:              true
  
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/Bruce-Connor/bruce-connor.github.io

pages_list:       
  About: '/about.html'
  Archive: '/archive.html'
  Feed: '/atom.xml'
