##########
### Start
##########

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            Endless Parentheses
tagline:          'Concise ramblings on Emacs productivity.'
url:              'http://endlessparentheses.com'
paginate:         15

baseurl:          /
author:
  name:           Artur Malabarba
  url:            https://github.com/Malabarba
  email:          artur@endlessparentheses.com
  twitter:        https://twitter.com/AMalabarba

# Content
excerpt_separator: "</p>"
timezone:         UTC
future:           false

# This doesn't work, had to implement my own solution.
# lsi:              true

# Related pages
related:
  excluded_tags:  ['init.el', 'emacs']
  max_number:     3

pages_list:
  About: ['/about.html', '/icons/favicon-bw.png']
  Archive: ['/archive.html', '/icons/envelope.png']
  RSS Feed: ['/atom.xml', '/icons/rss.png']
  Tag List: ['/tags.html', '/icons/tag.png']

media_list:
  Twitter:
    url: 'https://twitter.com/intent/tweet?via=AMalabarba&hashtags=emacs&url='
    icon: '/icons/twitter-black.png'
    title: '&text='
  Facebook:
    url: 'http://facebook.com/sharer.php?u='
    icon: '/icons/facebook.png'
  Google Plus:
    url: 'https://plus.google.com/share?hl=en&url='
    icon: '/icons/gplus-black.png'

projects:
  Paradox:
    url: 'https://github.com/Malabarba/paradox/'
    description: 'A modern and customizable Packages Menu.'
  Bug Hunter:
    url: 'https://github.com/Malabarba/elisp-bug-hunter/'
    description: 'Track down issues in your init file.'
  Names:
    url: 'https://github.com/Malabarba/names/'
    description: 'Namespaces for emacs-lisp.'
  smart-mode-line:
    url: 'https://github.com/Malabarba/smart-mode-line/'
    description: 'A powerful and beautiful mode-line.'
  # latex-extra:
  #   url: 'https://github.com/Malabarba/latex-extra/'
  #   description: 'A series of usability improvements for LaTeX-mode.'
  google-this:
    url: 'https://github.com/Malabarba/emacs-google-this/'
    description: 'Commands and keybinds for Googling at point.'
  Emacs Online Doc:
    url: 'http://doc.endlessparentheses.com/'
    description: 'An up-to-date online documentation of ALL Emacs functions and variables.'
  # Emacs Archive Tracker:
  #   url: 'http://tracker.endlessparentheses.com/'
  #   description: 'Statistics on the growth of Emacs package repositories.'

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
